using Dapper;
using MySqlConnector;
using CorpInsightsTW.Etl.Dtos.T187Ap07;

namespace CorpInsightsTW.Etl.Repositories.T187Ap07;

public class BasiRepository(string connectionString)
{
    private readonly string _connectionString = connectionString;

    /// <summary>
    /// 批次寫入或更新資產負債表-金融業 (t187ap07_basi)
    /// </summary>
    public async Task UpsertAsync(IEnumerable<BasiDto> dtos, CancellationToken cancellationToken = default)
    {
        if (dtos == null || !dtos.Any()) return;

        const string sql = @"
            INSERT INTO t187ap07_basi (
                year,
                quarter,
                listing_status,
                company_code,
                company_name,
                cash_and_cash_equivalents,
                due_from_central_bank_and_banks,
                financial_assets_at_fvtpl,
                financial_assets_at_fvoci,
                financial_assets_at_amortized_cost,
                derivative_financial_assets_for_hedging,
                reverse_repo,
                receivables,
                current_tax_assets,
                assets_held_for_sale,
                assets_for_distribution,
                discounts_and_loans,
                investments_using_equity_method,
                restricted_assets,
                other_financial_assets,
                property_and_equipment,
                right_of_use_assets,
                investment_property,
                intangible_assets,
                deferred_tax_assets,
                other_assets,
                total_assets_amount,
                deposits_from_central_bank_and_banks,
                due_to_central_bank_and_banks,
                financial_liabs_at_fvtpl,
                derivative_financial_liabs_for_hedging,
                repo_liabs,
                payables,
                current_tax_liabs,
                liabs_related_to_assets_held_for_sale,
                deposits_and_remittances,
                financial_bonds_payable,
                bonds_payable,
                preferred_stock_liabs,
                other_financial_liabs,
                provisions_for_liabs,
                lease_liabs,
                deferred_tax_liabs,
                other_liabs,
                total_liabs_amount,
                share_capital,
                security_token_equity,
                capital_surplus,
                retained_earnings,
                other_equity,
                treasury_stock,
                equity_attributable_to_owners_of_parent,
                predecessor_interests,
                equity_not_under_common_control,
                non_controlling_interests,
                total_equity_amount,
                pending_cancellation_shares,
                pre_received_shares_equivalent,
                parent_subsidiary_treasury_shares,
                net_value_per_share,
                updated_at
            ) VALUES (
                @Year,
                @Quarter,
                @ListingStatus,
                @CompanyCode,
                @CompanyName,
                @CashAndCashEquivalents,
                @DueFromCentralBankAndBanks,
                @FinancialAssetsAtFvtpl,
                @FinancialAssetsAtFvoci,
                @FinancialAssetsAtAmortizedCost,
                @DerivativeFinancialAssetsForHedging,
                @ReverseRepo,
                @Receivables,
                @CurrentTaxAssets,
                @AssetsHeldForSale,
                @AssetsForDistribution,
                @DiscountsAndLoans,
                @InvestmentsUsingEquityMethod,
                @RestrictedAssets,
                @OtherFinancialAssets,
                @PropertyAndEquipment,
                @RightOfUseAssets,
                @InvestmentProperty,
                @IntangibleAssets,
                @DeferredTaxAssets,
                @OtherAssets,
                @TotalAssetsAmount,
                @DepositsFromCentralBankAndBanks,
                @DueToCentralBankAndBanks,
                @FinancialLiabsAtFvtpl,
                @DerivativeFinancialLiabsForHedging,
                @RepoLiabs,
                @Payables,
                @CurrentTaxLiabs,
                @LiabsRelatedToAssetsHeldForSale,
                @DepositsAndRemittances,
                @FinancialBondsPayable,
                @BondsPayable,
                @PreferredStockLiabs,
                @OtherFinancialLiabs,
                @ProvisionsForLiabs,
                @LeaseLiabs,
                @DeferredTaxLiabs,
                @OtherLiabs,
                @TotalLiabsAmount,
                @ShareCapital,
                @SecurityTokenEquity,
                @CapitalSurplus,
                @RetainedEarnings,
                @OtherEquity,
                @TreasuryStock,
                @EquityAttributableToOwnersOfParent,
                @PredecessorInterests,
                @EquityNotUnderCommonControl,
                @NonControllingInterests,
                @TotalEquityAmount,
                @PendingCancellationShares,
                @PreReceivedSharesEquivalent,
                @ParentSubsidiaryTreasuryShares,
                @NetValuePerShare,
                NOW()
            )
            ON DUPLICATE KEY UPDATE
                listing_status                          = VALUES(listing_status),
                company_name                            = VALUES(company_name),
                cash_and_cash_equivalents               = VALUES(cash_and_cash_equivalents),
                due_from_central_bank_and_banks         = VALUES(due_from_central_bank_and_banks),
                financial_assets_at_fvtpl               = VALUES(financial_assets_at_fvtpl),
                financial_assets_at_fvoci               = VALUES(financial_assets_at_fvoci),
                financial_assets_at_amortized_cost      = VALUES(financial_assets_at_amortized_cost),
                derivative_financial_assets_for_hedging = VALUES(derivative_financial_assets_for_hedging),
                reverse_repo                            = VALUES(reverse_repo),
                receivables                             = VALUES(receivables),
                current_tax_assets                      = VALUES(current_tax_assets),
                assets_held_for_sale                    = VALUES(assets_held_for_sale),
                assets_for_distribution                 = VALUES(assets_for_distribution),
                discounts_and_loans                     = VALUES(discounts_and_loans),
                investments_using_equity_method         = VALUES(investments_using_equity_method),
                restricted_assets                       = VALUES(restricted_assets),
                other_financial_assets                  = VALUES(other_financial_assets),
                property_and_equipment                  = VALUES(property_and_equipment),
                right_of_use_assets                     = VALUES(right_of_use_assets),
                investment_property                     = VALUES(investment_property),
                intangible_assets                       = VALUES(intangible_assets),
                deferred_tax_assets                     = VALUES(deferred_tax_assets),
                other_assets                            = VALUES(other_assets),
                total_assets_amount                     = VALUES(total_assets_amount),
                deposits_from_central_bank_and_banks    = VALUES(deposits_from_central_bank_and_banks),
                due_to_central_bank_and_banks           = VALUES(due_to_central_bank_and_banks),
                financial_liabs_at_fvtpl                = VALUES(financial_liabs_at_fvtpl),
                derivative_financial_liabs_for_hedging  = VALUES(derivative_financial_liabs_for_hedging),
                repo_liabs                              = VALUES(repo_liabs),
                payables                                = VALUES(payables),
                current_tax_liabs                       = VALUES(current_tax_liabs),
                liabs_related_to_assets_held_for_sale   = VALUES(liabs_related_to_assets_held_for_sale),
                deposits_and_remittances                = VALUES(deposits_and_remittances),
                financial_bonds_payable                 = VALUES(financial_bonds_payable),
                bonds_payable                           = VALUES(bonds_payable),
                preferred_stock_liabs                   = VALUES(preferred_stock_liabs),
                other_financial_liabs                   = VALUES(other_financial_liabs),
                provisions_for_liabs                    = VALUES(provisions_for_liabs),
                lease_liabs                             = VALUES(lease_liabs),
                deferred_tax_liabs                      = VALUES(deferred_tax_liabs),
                other_liabs                             = VALUES(other_liabs),
                total_liabs_amount                      = VALUES(total_liabs_amount),
                share_capital                           = VALUES(share_capital),
                security_token_equity                   = VALUES(security_token_equity),
                capital_surplus                         = VALUES(capital_surplus),
                retained_earnings                       = VALUES(retained_earnings),
                other_equity                            = VALUES(other_equity),
                treasury_stock                          = VALUES(treasury_stock),
                equity_attributable_to_owners_of_parent = VALUES(equity_attributable_to_owners_of_parent),
                predecessor_interests                   = VALUES(predecessor_interests),
                equity_not_under_common_control         = VALUES(equity_not_under_common_control),
                non_controlling_interests               = VALUES(non_controlling_interests),
                total_equity_amount                     = VALUES(total_equity_amount),
                pending_cancellation_shares             = VALUES(pending_cancellation_shares),
                pre_received_shares_equivalent          = VALUES(pre_received_shares_equivalent),
                parent_subsidiary_treasury_shares       = VALUES(parent_subsidiary_treasury_shares),
                net_value_per_share                     = VALUES(net_value_per_share),
                updated_at                              = NOW();";

        using var connection = new MySqlConnection(_connectionString);
        await connection.OpenAsync(cancellationToken);

        foreach (var chunk in dtos.Chunk(1000))
        {
            var command = new CommandDefinition(sql, chunk, cancellationToken: cancellationToken);
            await connection.ExecuteAsync(command);
        }
    }
}