using Dapper;
using MySqlConnector;
using CorpInsightsTW.Etl.Dtos.T187Ap07;

namespace CorpInsightsTW.Etl.Repositories.T187Ap07;

public class InsRepository(string connectionString)
{
    private readonly string _connectionString = connectionString;

    /// <summary>
    /// 批次寫入或更新資產負債表-保險業 (t187ap07_ins)
    /// </summary>
    public async Task UpsertAsync(IEnumerable<InsDto> dtos, CancellationToken cancellationToken = default)
    {
        if (dtos == null || !dtos.Any()) return;

        const string sql = @"
            INSERT INTO t187ap07_ins (
                year,
                quarter,
                listing_status,
                company_code,
                company_name,
                cash_and_cash_equivalents,
                receivables,
                current_tax_assets,
                assets_held_for_sale,
                assets_for_distribution,
                financial_assets_at_fvtpl,
                financial_assets_at_fvoci,
                financial_assets_at_amortized_cost,
                derivative_financial_assets_for_hedging,
                investments_using_equity_method,
                other_financial_assets,
                investment_property,
                loans,
                insurance_contract_assets,
                reinsurance_contract_assets,
                property_and_equipment,
                right_of_use_assets,
                intangible_assets,
                deferred_tax_assets,
                other_assets,
                assets_on_separate_accounts,
                total_assets,
                short_term_debts,
                payables,
                current_tax_liabs,
                liabs_related_to_assets_held_for_sale,
                financial_liabs_at_fvtpl,
                derivative_financial_liabs_for_hedging,
                bonds_payable,
                preferred_stock_liabs,
                provisions,
                other_financial_liabs,
                lease_liabs,
                deferred_tax_liabs,
                other_liabs,
                total_liabs,
                share_capital,
                security_token_equity,
                capital_surplus,
                retained_earnings,
                other_equity,
                treasury_stock,
                equity_attributable_to_owners_of_parent,
                predecessor_interests,
                equity_not_under_common_control,
                non_controlling_interests,
                total_equity,
                total_liabs_and_equity,
                pending_cancellation_shares,
                pre_received_shares_equivalent,
                parent_subsidiary_treasury_shares,
                net_value_per_share,
                updated_at
            ) VALUES (
                @Year,
                @Quarter,
                @ListingStatus,
                @CompanyCode,
                @CompanyName,
                @CashAndCashEquivalents,
                @Receivables,
                @CurrentTaxAssets,
                @AssetsHeldForSale,
                @AssetsForDistribution,
                @FinancialAssetsAtFvtpl,
                @FinancialAssetsAtFvoci,
                @FinancialAssetsAtAmortizedCost,
                @DerivativeFinancialAssetsForHedging,
                @InvestmentsUsingEquityMethod,
                @OtherFinancialAssets,
                @InvestmentProperty,
                @Loans,
                @InsuranceContractAssets,
                @ReinsuranceContractAssets,
                @PropertyAndEquipment,
                @RightOfUseAssets,
                @IntangibleAssets,
                @DeferredTaxAssets,
                @OtherAssets,
                @AssetsOnSeparateAccounts,
                @TotalAssets,
                @ShortTermDebts,
                @Payables,
                @CurrentTaxLiabs,
                @LiabsRelatedToAssetsHeldForSale,
                @FinancialLiabsAtFvtpl,
                @DerivativeFinancialLiabsForHedging,
                @BondsPayable,
                @PreferredStockLiabs,
                @Provisions,
                @OtherFinancialLiabs,
                @LeaseLiabs,
                @DeferredTaxLiabs,
                @OtherLiabs,
                @TotalLiabs,
                @ShareCapital,
                @SecurityTokenEquity,
                @CapitalSurplus,
                @RetainedEarnings,
                @OtherEquity,
                @TreasuryStock,
                @EquityAttributableToOwnersOfParent,
                @PredecessorInterests,
                @EquityNotUnderCommonControl,
                @NonControllingInterests,
                @TotalEquity,
                @TotalLiabsAndEquity,
                @PendingCancellationShares,
                @PreReceivedSharesEquivalent,
                @ParentSubsidiaryTreasuryShares,
                @NetValuePerShare,
                NOW()
            )
            ON DUPLICATE KEY UPDATE
                listing_status                          = VALUES(listing_status),
                company_name                            = VALUES(company_name),
                cash_and_cash_equivalents               = VALUES(cash_and_cash_equivalents),
                receivables                             = VALUES(receivables),
                current_tax_assets                      = VALUES(current_tax_assets),
                assets_held_for_sale                    = VALUES(assets_held_for_sale),
                assets_for_distribution                 = VALUES(assets_for_distribution),
                financial_assets_at_fvtpl               = VALUES(financial_assets_at_fvtpl),
                financial_assets_at_fvoci               = VALUES(financial_assets_at_fvoci),
                financial_assets_at_amortized_cost      = VALUES(financial_assets_at_amortized_cost),
                derivative_financial_assets_for_hedging = VALUES(derivative_financial_assets_for_hedging),
                investments_using_equity_method         = VALUES(investments_using_equity_method),
                other_financial_assets                  = VALUES(other_financial_assets),
                investment_property                     = VALUES(investment_property),
                loans                                   = VALUES(loans),
                insurance_contract_assets               = VALUES(insurance_contract_assets),
                reinsurance_contract_assets             = VALUES(reinsurance_contract_assets),
                property_and_equipment                  = VALUES(property_and_equipment),
                right_of_use_assets                     = VALUES(right_of_use_assets),
                intangible_assets                       = VALUES(intangible_assets),
                deferred_tax_assets                     = VALUES(deferred_tax_assets),
                other_assets                            = VALUES(other_assets),
                assets_on_separate_accounts             = VALUES(assets_on_separate_accounts),
                total_assets                            = VALUES(total_assets),
                short_term_debts                        = VALUES(short_term_debts),
                payables                                = VALUES(payables),
                current_tax_liabs                       = VALUES(current_tax_liabs),
                liabs_related_to_assets_held_for_sale   = VALUES(liabs_related_to_assets_held_for_sale),
                financial_liabs_at_fvtpl                = VALUES(financial_liabs_at_fvtpl),
                derivative_financial_liabs_for_hedging  = VALUES(derivative_financial_liabs_for_hedging),
                bonds_payable                           = VALUES(bonds_payable),
                preferred_stock_liabs                   = VALUES(preferred_stock_liabs),
                provisions                              = VALUES(provisions),
                other_financial_liabs                   = VALUES(other_financial_liabs),
                lease_liabs                             = VALUES(lease_liabs),
                deferred_tax_liabs                      = VALUES(deferred_tax_liabs),
                other_liabs                             = VALUES(other_liabs),
                total_liabs                             = VALUES(total_liabs),
                share_capital                           = VALUES(share_capital),
                security_token_equity                   = VALUES(security_token_equity),
                capital_surplus                         = VALUES(capital_surplus),
                retained_earnings                       = VALUES(retained_earnings),
                other_equity                            = VALUES(other_equity),
                treasury_stock                          = VALUES(treasury_stock),
                equity_attributable_to_owners_of_parent = VALUES(equity_attributable_to_owners_of_parent),
                predecessor_interests                   = VALUES(predecessor_interests),
                equity_not_under_common_control         = VALUES(equity_not_under_common_control),
                non_controlling_interests               = VALUES(non_controlling_interests),
                total_equity                            = VALUES(total_equity),
                total_liabs_and_equity                  = VALUES(total_liabs_and_equity),
                pending_cancellation_shares             = VALUES(pending_cancellation_shares),
                pre_received_shares_equivalent          = VALUES(pre_received_shares_equivalent),
                parent_subsidiary_treasury_shares       = VALUES(parent_subsidiary_treasury_shares),
                net_value_per_share                     = VALUES(net_value_per_share),
                updated_at                              = NOW();";

        using var connection = new MySqlConnection(_connectionString);
        await connection.OpenAsync(cancellationToken);

        foreach (var chunk in dtos.Chunk(1000))
        {
            var command = new CommandDefinition(sql, chunk, cancellationToken: cancellationToken);
            await connection.ExecuteAsync(command);
        }
    }
}